In [12]:
import pandas as pd
import numpy as np
import os

In [13]:
os.chdir('/Users/alisdghnia/Desktop/School - Graduate/Advanced Database Management - Spring 2023/Final Project')

In [14]:
df = pd.read_csv('Crypto Data.csv')
df

,name_name,name_symbol,name_rank,name_Price,name_oneday,name_oneweek,name_marketcapital,name_Volume,name_circulationsupply,name_cryptoname_symbol,name_fullmarketcap,name_maxsupply,name_onedaylow,name_onedayhigh,name_volumemarketcap,name_marketdominance,name_ROI_onemonth,name_Pricechange
0,Bitcoin,1 BTC,1,"$20,414.69",1.34%,9.55%,"$394,316,882,491","$6,297,828,806","19,315,350 BTC",BitcoinBTC,"$428,671,110,000","21,000,000 BTC","$20,065.34","$20,535.46",0.02%,40.08%,-6.10%,$267.92
1,Ethereum,2 ETH,2,"$1,460.98",1.90%,7.43%,"$178,785,770,748","$4,085,407,711","122,373,866 ETH",EthereumETH,"$178,752,729,804",NaN,"$1,429.22","$1,477.38",0.02%,18.17%,-4.03%,$26.95
2,Tether,3 USDT,3,$1.01,0.57%,0.73%,"$72,635,948,967","$12,863,544,876","72,116,708,665 USDT",TetherUSDT,"$73,668,387,038",NaN,$1,$1.01,0.18%,7.38%,NaN,$0.01
3,Binance Coin,4 BNB,4,$275.15,0.41%,4.37%,"$43,444,185,760","$279,219,432","157,892,734 BNB",Binance CoinBNB,"$55,006,000,000","200,000,000 BNB",$271.60,$278.45,0.01%,4.41%,-10.72%,$0.99
4,USD Coin,5 USDC,5,$0.96,3.09%,5.05%,"$38,927,636,057","$3,670,430,628","40,736,329,068 USDC",USD CoinUSDC,"$38,915,415,158",NaN,$0.93,$0.98,0.09%,3.96%,-4.38%,$0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FTX Token,96 FTT,96,$1.04,1.86%,22.75%,"$340,472,219","$3,484,697","328,895,112 FTT",FTX TokenFTT,"$363,862,059","352,170,015 FTT",$1,$1.04,0.01%,0.03%,-36.12%,$0.02
96,Nexo,97 NEXO,97,$0.58,1.12%,10.86%,"$323,064,006","$3,058,157","560,000,011 NEXO",NexoNEXO,"$578,400,000","1,000,000,000 NEXO",$0.56,$0.59,0.01%,0.03%,-20.04%,$0.02
97,Threshold Network,98 T,98,$0.03,0.95%,25.93%,"$314,360,000","$7,917,754","10,000,000,000 T",Threshold NetworkT,"$329,802,975","10,515,000,000 T",$0.03,$0.03,0.03%,0.03%,-23.67%,$0.00
98,SSV Network,99 SSV,99,$30.98,5.74%,20.54%,"$309,790,000","$29,545,113","10,000,000 SSV",SSV NetworkSSV,"$339,791,121",NaN,$28.77,$33.20,0.10%,0.03%,NaN,$1.24
99,Basic Attention Token,100 BAT,100,$0.21,0.10%,21.24%,"$307,549,619","$10,668,399","1,499,510,577 BAT",Basic Attention TokenBAT,"$307,350,000","1,500,000,000 BAT",$0.20,$0.21,0.03%,0.03%,-24.76%,$0.00

In [15]:
df.columns

Index(['name_name', 'name_symbol', 'name_rank', 'name_Price', 'name_oneday',
       'name_oneweek', 'name_marketcapital', 'name_Volume',
       'name_circulationsupply', 'name_cryptoname_symbol',
       'name_fullmarketcap', 'name_maxsupply', 'name_onedaylow',
       'name_onedayhigh', 'name_volumemarketcap', 'name_marketdominance',
       'name_ROI_onemonth', 'name_Pricechange'],
      dtype='object')

In [16]:
df.columns = ['name', 'symbol', 'rank', 'price (USD)', 'oneday (%)', 'oneweek (%)', 'marketcap (USD)', 'volume (USD)', 'circulating_supply (Crypto)', 'crypto_name_symbol', 'full_marketcap (USD)', 'max_supply (Crypto)',
              'oneday_low (USD)', 'oneday_high (USD)', 'volume_marketcap (%)', 'market_dominance (%)', 'onemonth_ROI (%)', 'price_change (USD)']

In [17]:
df = df.drop('crypto_name_symbol', axis=1)
df

,name,symbol,rank,price (USD),oneday (%),oneweek (%),marketcap (USD),volume (USD),circulating_supply (Crypto),full_marketcap (USD),max_supply (Crypto),oneday_low (USD),oneday_high (USD),volume_marketcap (%),market_dominance (%),onemonth_ROI (%),price_change (USD)
0,Bitcoin,1 BTC,1,"$20,414.69",1.34%,9.55%,"$394,316,882,491","$6,297,828,806","19,315,350 BTC","$428,671,110,000","21,000,000 BTC","$20,065.34","$20,535.46",0.02%,40.08%,-6.10%,$267.92
1,Ethereum,2 ETH,2,"$1,460.98",1.90%,7.43%,"$178,785,770,748","$4,085,407,711","122,373,866 ETH","$178,752,729,804",NaN,"$1,429.22","$1,477.38",0.02%,18.17%,-4.03%,$26.95
2,Tether,3 USDT,3,$1.01,0.57%,0.73%,"$72,635,948,967","$12,863,544,876","72,116,708,665 USDT","$73,668,387,038",NaN,$1,$1.01,0.18%,7.38%,NaN,$0.01
3,Binance Coin,4 BNB,4,$275.15,0.41%,4.37%,"$43,444,185,760","$279,219,432","157,892,734 BNB","$55,006,000,000","200,000,000 BNB",$271.60,$278.45,0.01%,4.41%,-10.72%,$0.99
4,USD Coin,5 USDC,5,$0.96,3.09%,5.05%,"$38,927,636,057","$3,670,430,628","40,736,329,068 USDC","$38,915,415,158",NaN,$0.93,$0.98,0.09%,3.96%,-4.38%,$0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FTX Token,96 FTT,96,$1.04,1.86%,22.75%,"$340,472,219","$3,484,697","328,895,112 FTT","$363,862,059","352,170,015 FTT",$1,$1.04,0.01%,0.03%,-36.12%,$0.02
96,Nexo,97 NEXO,97,$0.58,1.12%,10.86%,"$323,064,006","$3,058,157","560,000,011 NEXO","$578,400,000","1,000,000,000 NEXO",$0.56,$0.59,0.01%,0.03%,-20.04%,$0.02
97,Threshold Network,98 T,98,$0.03,0.95%,25.93%,"$314,360,000","$7,917,754","10,000,000,000 T","$329,802,975","10,515,000,000 T",$0.03,$0.03,0.03%,0.03%,-23.67%,$0.00
98,SSV Network,99 SSV,99,$30.98,5.74%,20.54%,"$309,790,000","$29,545,113","10,000,000 SSV","$339,791,121",NaN,$28.77,$33.20,0.10%,0.03%,NaN,$1.24
99,Basic Attention Token,100 BAT,100,$0.21,0.10%,21.24%,"$307,549,619","$10,668,399","1,499,510,577 BAT","$307,350,000","1,500,000,000 BAT",$0.20,$0.21,0.03%,0.03%,-24.76%,$0.00

In [18]:
# df.to_csv('Cleaned Crypto Data.csv', index=False)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         100 non-null    object
 1   symbol                       100 non-null    object
 2   rank                         100 non-null    int64
 3   price (USD)                  100 non-null    object
 4   oneday (%)                   100 non-null    object
 5   oneweek (%)                  100 non-null    object
 6   marketcap (USD)              100 non-null    object
 7   volume (USD)                 100 non-null    object
 8   circulating_supply (Crypto)  100 non-null    object
 9   full_marketcap (USD)         100 non-null    object
 10  max_supply (Crypto)          74 non-null     object
 11  oneday_low (USD)             100 non-null    object
 12  oneday_high (USD)            100 non-null    object
 13  volume_marketcap (%)         100 non-null    object
 14  market_dominance (%)         100 non-null    object
 15  onemonth_ROI (%)             85 non-null     object
 16  price_change (USD)           100 non-null    object
dtypes: int64(1), object(16)
memory usage: 13.4+ KB

In [20]:
# get rid of $ and , in all columns
for i in df.columns:
    try:    
        df[i] = df[i].str.replace('$', '')
        df[i] = df[i].str.replace(',', '')
        df[i] = df[i].str.replace('%', '')
        df[i] = df[i].str.replace(' ', '')
        # df[i] = df[i].str.replace('N/A', '0')
    except Exception:
        pass
df

/var/folders/_9/qq7pw_fx125c812gfv1wl_180000gn/T/ipykernel_72055/2134033481.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df[i] = df[i].str.replace('$', '')

,name,symbol,rank,price (USD),oneday (%),oneweek (%),marketcap (USD),volume (USD),circulating_supply (Crypto),full_marketcap (USD),max_supply (Crypto),oneday_low (USD),oneday_high (USD),volume_marketcap (%),market_dominance (%),onemonth_ROI (%),price_change (USD)
0,Bitcoin,1BTC,1,20414.69,1.34,9.55,394316882491,6297828806,19315350BTC,428671110000,21000000BTC,20065.34,20535.46,0.02,40.08,-6.10,267.92
1,Ethereum,2ETH,2,1460.98,1.90,7.43,178785770748,4085407711,122373866ETH,178752729804,NaN,1429.22,1477.38,0.02,18.17,-4.03,26.95
2,Tether,3USDT,3,1.01,0.57,0.73,72635948967,12863544876,72116708665USDT,73668387038,NaN,1,1.01,0.18,7.38,NaN,0.01
3,BinanceCoin,4BNB,4,275.15,0.41,4.37,43444185760,279219432,157892734BNB,55006000000,200000000BNB,271.60,278.45,0.01,4.41,-10.72,0.99
4,USDCoin,5USDC,5,0.96,3.09,5.05,38927636057,3670430628,40736329068USDC,38915415158,NaN,0.93,0.98,0.09,3.96,-4.38,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FTXToken,96FTT,96,1.04,1.86,22.75,340472219,3484697,328895112FTT,363862059,352170015FTT,1,1.04,0.01,0.03,-36.12,0.02
96,Nexo,97NEXO,97,0.58,1.12,10.86,323064006,3058157,560000011NEXO,578400000,1000000000NEXO,0.56,0.59,0.01,0.03,-20.04,0.02
97,ThresholdNetwork,98T,98,0.03,0.95,25.93,314360000,7917754,10000000000T,329802975,10515000000T,0.03,0.03,0.03,0.03,-23.67,0.00
98,SSVNetwork,99SSV,99,30.98,5.74,20.54,309790000,29545113,10000000SSV,339791121,NaN,28.77,33.20,0.10,0.03,NaN,1.24
99,BasicAttentionToken,100BAT,100,0.21,0.10,21.24,307549619,10668399,1499510577BAT,307350000,1500000000BAT,0.20,0.21,0.03,0.03,-24.76,0.00

In [21]:
# get rid of numbers in symbol column
df['symbol'] = df['symbol'].str.replace('[0-9]', '')
df

/var/folders/_9/qq7pw_fx125c812gfv1wl_180000gn/T/ipykernel_72055/2231127593.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['symbol'] = df['symbol'].str.replace('[0-9]', '')

,name,symbol,rank,price (USD),oneday (%),oneweek (%),marketcap (USD),volume (USD),circulating_supply (Crypto),full_marketcap (USD),max_supply (Crypto),oneday_low (USD),oneday_high (USD),volume_marketcap (%),market_dominance (%),onemonth_ROI (%),price_change (USD)
0,Bitcoin,BTC,1,20414.69,1.34,9.55,394316882491,6297828806,19315350BTC,428671110000,21000000BTC,20065.34,20535.46,0.02,40.08,-6.10,267.92
1,Ethereum,ETH,2,1460.98,1.90,7.43,178785770748,4085407711,122373866ETH,178752729804,NaN,1429.22,1477.38,0.02,18.17,-4.03,26.95
2,Tether,USDT,3,1.01,0.57,0.73,72635948967,12863544876,72116708665USDT,73668387038,NaN,1,1.01,0.18,7.38,NaN,0.01
3,BinanceCoin,BNB,4,275.15,0.41,4.37,43444185760,279219432,157892734BNB,55006000000,200000000BNB,271.60,278.45,0.01,4.41,-10.72,0.99
4,USDCoin,USDC,5,0.96,3.09,5.05,38927636057,3670430628,40736329068USDC,38915415158,NaN,0.93,0.98,0.09,3.96,-4.38,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FTXToken,FTT,96,1.04,1.86,22.75,340472219,3484697,328895112FTT,363862059,352170015FTT,1,1.04,0.01,0.03,-36.12,0.02
96,Nexo,NEXO,97,0.58,1.12,10.86,323064006,3058157,560000011NEXO,578400000,1000000000NEXO,0.56,0.59,0.01,0.03,-20.04,0.02
97,ThresholdNetwork,T,98,0.03,0.95,25.93,314360000,7917754,10000000000T,329802975,10515000000T,0.03,0.03,0.03,0.03,-23.67,0.00
98,SSVNetwork,SSV,99,30.98,5.74,20.54,309790000,29545113,10000000SSV,339791121,NaN,28.77,33.20,0.10,0.03,NaN,1.24
99,BasicAttentionToken,BAT,100,0.21,0.10,21.24,307549619,10668399,1499510577BAT,307350000,1500000000BAT,0.20,0.21,0.03,0.03,-24.76,0.00

In [22]:
# get rid of letters in circulating_supply and max_supply columns
df['circulating_supply (Crypto)'] = df['circulating_supply (Crypto)'].str.replace('[a-zA-Z]', '')
df['max_supply (Crypto)'] = df['max_supply (Crypto)'].str.replace('[a-zA-Z]', '')
df

/var/folders/_9/qq7pw_fx125c812gfv1wl_180000gn/T/ipykernel_72055/3886335280.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['circulating_supply (Crypto)'] = df['circulating_supply (Crypto)'].str.replace('[a-zA-Z]', '')
/var/folders/_9/qq7pw_fx125c812gfv1wl_180000gn/T/ipykernel_72055/3886335280.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df['max_supply (Crypto)'] = df['max_supply (Crypto)'].str.replace('[a-zA-Z]', '')

,name,symbol,rank,price (USD),oneday (%),oneweek (%),marketcap (USD),volume (USD),circulating_supply (Crypto),full_marketcap (USD),max_supply (Crypto),oneday_low (USD),oneday_high (USD),volume_marketcap (%),market_dominance (%),onemonth_ROI (%),price_change (USD)
0,Bitcoin,BTC,1,20414.69,1.34,9.55,394316882491,6297828806,19315350,428671110000,21000000,20065.34,20535.46,0.02,40.08,-6.10,267.92
1,Ethereum,ETH,2,1460.98,1.90,7.43,178785770748,4085407711,122373866,178752729804,NaN,1429.22,1477.38,0.02,18.17,-4.03,26.95
2,Tether,USDT,3,1.01,0.57,0.73,72635948967,12863544876,72116708665,73668387038,NaN,1,1.01,0.18,7.38,NaN,0.01
3,BinanceCoin,BNB,4,275.15,0.41,4.37,43444185760,279219432,157892734,55006000000,200000000,271.60,278.45,0.01,4.41,-10.72,0.99
4,USDCoin,USDC,5,0.96,3.09,5.05,38927636057,3670430628,40736329068,38915415158,NaN,0.93,0.98,0.09,3.96,-4.38,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FTXToken,FTT,96,1.04,1.86,22.75,340472219,3484697,328895112,363862059,352170015,1,1.04,0.01,0.03,-36.12,0.02
96,Nexo,NEXO,97,0.58,1.12,10.86,323064006,3058157,560000011,578400000,1000000000,0.56,0.59,0.01,0.03,-20.04,0.02
97,ThresholdNetwork,T,98,0.03,0.95,25.93,314360000,7917754,10000000000,329802975,10515000000,0.03,0.03,0.03,0.03,-23.67,0.00
98,SSVNetwork,SSV,99,30.98,5.74,20.54,309790000,29545113,10000000,339791121,NaN,28.77,33.20,0.10,0.03,NaN,1.24
99,BasicAttentionToken,BAT,100,0.21,0.10,21.24,307549619,10668399,1499510577,307350000,1500000000,0.20,0.21,0.03,0.03,-24.76,0.00

In [26]:
# turn all columns into floats except for name, symbol, and rank with 2 decimal places
for i in df.columns:
    try:
        df[i] = df[i].astype(float)
        df[i] = df[i].round(2)
    except Exception:
        pass

df['rank'] = df['rank'].astype(int)

df

,name,symbol,rank,price (USD),oneday (%),oneweek (%),marketcap (USD),volume (USD),circulating_supply (Crypto),full_marketcap (USD),max_supply (Crypto),oneday_low (USD),oneday_high (USD),volume_marketcap (%),market_dominance (%),onemonth_ROI (%),price_change (USD)
0,Bitcoin,BTC,1,20414.69,1.34,9.55,3.943169e+11,6.297829e+09,1.931535e+07,4.286711e+11,2.100000e+07,20065.34,20535.46,0.02,40.08,-6.10,267.92
1,Ethereum,ETH,2,1460.98,1.90,7.43,1.787858e+11,4.085408e+09,1.223739e+08,1.787527e+11,NaN,1429.22,1477.38,0.02,18.17,-4.03,26.95
2,Tether,USDT,3,1.01,0.57,0.73,7.263595e+10,1.286354e+10,7.211671e+10,7.366839e+10,NaN,1.00,1.01,0.18,7.38,NaN,0.01
3,BinanceCoin,BNB,4,275.15,0.41,4.37,4.344419e+10,2.792194e+08,1.578927e+08,5.500600e+10,2.000000e+08,271.60,278.45,0.01,4.41,-10.72,0.99
4,USDCoin,USDC,5,0.96,3.09,5.05,3.892764e+10,3.670431e+09,4.073633e+10,3.891542e+10,NaN,0.93,0.98,0.09,3.96,-4.38,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,FTXToken,FTT,96,1.04,1.86,22.75,3.404722e+08,3.484697e+06,3.288951e+08,3.638621e+08,3.521700e+08,1.00,1.04,0.01,0.03,-36.12,0.02
96,Nexo,NEXO,97,0.58,1.12,10.86,3.230640e+08,3.058157e+06,5.600000e+08,5.784000e+08,1.000000e+09,0.56,0.59,0.01,0.03,-20.04,0.02
97,ThresholdNetwork,T,98,0.03,0.95,25.93,3.143600e+08,7.917754e+06,1.000000e+10,3.298030e+08,1.051500e+10,0.03,0.03,0.03,0.03,-23.67,0.00
98,SSVNetwork,SSV,99,30.98,5.74,20.54,3.097900e+08,2.954511e+07,1.000000e+07,3.397911e+08,NaN,28.77,33.20,0.10,0.03,NaN,1.24
99,BasicAttentionToken,BAT,100,0.21,0.10,21.24,3.075496e+08,1.066840e+07,1.499511e+09,3.073500e+08,1.500000e+09,0.20,0.21,0.03,0.03,-24.76,0.00

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         100 non-null    object
 1   symbol                       100 non-null    object
 2   rank                         100 non-null    int64
 3   price (USD)                  100 non-null    float64
 4   oneday (%)                   100 non-null    float64
 5   oneweek (%)                  100 non-null    float64
 6   marketcap (USD)              100 non-null    float64
 7   volume (USD)                 100 non-null    float64
 8   circulating_supply (Crypto)  100 non-null    float64
 9   full_marketcap (USD)         100 non-null    float64
 10  max_supply (Crypto)          74 non-null     float64
 11  oneday_low (USD)             100 non-null    float64
 12  oneday_high (USD)            100 non-null    float64
 13  volume_marketcap (%)         100 non-null    float64
 14  market_dominance (%)         100 non-null    float64
 15  onemonth_ROI (%)             85 non-null     float64
 16  price_change (USD)           100 non-null    object
dtypes: float64(13), int64(1), object(3)
memory usage: 13.4+ KB

In [28]:
df.to_csv('Cleaned Crypto Data.csv', index=False)